version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

volumes:
  postgres:
